version: '3.7'
services:
  web:
    build:
      context: ./web
    volumes:
      - ./web:/usr/src/app/
    ports:
      - 3003:3003
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST="postgres"
      - DATABASE_USER="postgres"
      - PGHOST="postgres"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app/
      - server_node_modules:/usr/src/app/node_modules
      - ./web/static:/usr/src/web/static
    ports:
      - 3000:3000
      - 3001:3001

  postgres:
    image: postgres:12.0
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432

volumes:
  server_node_modules:

