version: '3.8'
services:
  web:
    build:
      context: ./web
    volumes:
      - ./web:/usr/src/app/
    ports:
      - 3003:3003
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST="postgres"
      - DATABASE_USER="postgres"
      - PGHOST="postgres"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/config:/usr/src/app/config
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/start.sh:/usr/src/app/start.sh
      - ./frontend/package-lock.json:/usr/src/app/package-lock.json
      - ./frontend/package.json:/usr/src/app/package.json
      - ./frontend/scripts:/usr/src/app/scripts
      - ./web/static:/usr/src/web/static
    ports:
      - 3000:3000
      - 3001:3001

  postgres:
    image: postgres:12.0
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432

volumes:
  node_modules:
